import React, { useState } from 'react';
import ReactDOM from 'react-dom';
import { FileText, Plus, Search, Download, Edit, Trash2, Eye, X, MoreVertical } from 'lucide-react';
import { INVOICE_STATUS_COLORS } from '../utils/constants';
import { formatDate, formatCurrency } from '../utils/vendorUtils';

const VendorInvoicesView = ({ vendor, invoices, onSubmitInvoice, onEditInvoice, onDeleteInvoice }) => {
  const [showForm, setShowForm] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [editingInvoice, setEditingInvoice] = useState(null);
  const [viewingInvoice, setViewingInvoice] = useState(null);
  const [openDropdown, setOpenDropdown] = useState(null);
  const [dropdownPosition, setDropdownPosition] = useState({ top: 0, right: 0 });
  const [deleteConfirmModal, setDeleteConfirmModal] = useState(null);
  const [formData, setFormData] = useState({
    invoiceDate: '',
    dueDate: '',
    amount: '',
    description: '',
    notes: ''
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    let success;
    if (editingInvoice) {
      success = await onEditInvoice(editingInvoice.id, formData);
    } else {
      success = await onSubmitInvoice(formData);
    }
    
    if (success) {
      setFormData({
        invoiceDate: '',
        dueDate: '',
        amount: '',
        description: '',
        notes: ''
      });
      setShowForm(false);
      setEditingInvoice(null);
    }
  };

  const handleEdit = (invoice) => {
    setEditingInvoice(invoice);
    setFormData({
      invoiceDate: invoice.invoiceDate,
      dueDate: invoice.dueDate,
      amount: invoice.amount,
      description: invoice.description,
      notes: invoice.notes || ''
    });
    setShowForm(true);
    setOpenDropdown(null);
  };

  const handleView = (invoice) => {
    setViewingInvoice(invoice);
    setOpenDropdown(null);
  };

  const handleDelete = (invoice) => {
    setDeleteConfirmModal(invoice);
    setOpenDropdown(null);
  };

  const confirmDelete = async () => {
    if (deleteConfirmModal) {
      await onDeleteInvoice(deleteConfirmModal.id);
      setDeleteConfirmModal(null);
    }
  };

  const handleDownload = (invoice) => {
    const invoiceText = `
INVOICE

Invoice Number: ${invoice.invoiceNumber}
Invoice Date: ${formatDate(invoice.invoiceDate)}
Due Date: ${formatDate(invoice.dueDate)}
Amount: ${formatCurrency(invoice.amount)}

Vendor: ${vendor.companyName}
Vendor Code: ${vendor.id}

Description:
${invoice.description}

${invoice.notes ? `Notes:\n${invoice.notes}` : ''}

Status: ${invoice.status}
Submitted: ${formatDate(invoice.submittedAt)}

---
Generated by Onction Vendor Portal
    `.trim();

    const blob = new Blob([invoiceText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${invoice.invoiceNumber}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setOpenDropdown(null);
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const filteredInvoices = invoices.filter(invoice =>
    invoice.invoiceNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
    invoice.description.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const getStatusBadge = (status) => {
    const colors = INVOICE_STATUS_COLORS[status] || { bg: 'bg-gray-100', text: 'text-gray-800' };
    return (
      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${colors.bg} ${colors.text}`}>
        {status}
      </span>
    );
  };

  const canEdit = (invoice) => {
    return invoice.status === 'Submitted' || invoice.status === 'Pending Approval';
  };

  const canDelete = (invoice) => {
    return invoice.status === 'Submitted';
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Invoices</h1>
          <p className="text-gray-600 mt-1">Manage and track your invoices</p>
        </div>
        <button
          onClick={() => {
            setShowForm(!showForm);
            setEditingInvoice(null);
            setFormData({
              invoiceDate: '',
              dueDate: '',
              amount: '',
              description: '',
              notes: ''
            });
          }}
          disabled={vendor.status !== 'Approved'}
          className="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
        >
          <Plus size={20} />
          Submit Invoice
        </button>
      </div>

      {vendor.status !== 'Approved' && (
        <div className="bg-yellow-50 border-l-4 border-yellow-500 p-4 rounded-lg">
          <p className="text-sm text-yellow-800">
            You need to be approved before submitting invoices. Please wait for admin approval.
          </p>
        </div>
      )}

      {/* Submit/Edit Invoice Form */}
      {showForm && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <h2 className="text-xl font-bold text-gray-900 mb-4">
            {editingInvoice ? `Edit Invoice ${editingInvoice.invoiceNumber}` : 'Submit New Invoice'}
          </h2>
          {!editingInvoice && (
            <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-lg mb-4">
              <p className="text-sm text-blue-800">
                <strong>Invoice Number:</strong> Will be auto-generated (e.g., 001, 002, 003...)
              </p>
            </div>
          )}
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Amount (NGN) *
                </label>
                <input
                  type="number"
                  name="amount"
                  required
                  value={formData.amount}
                  onChange={handleChange}
                  placeholder="50000"
                  min="0"
                  step="0.01"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Invoice Date *
                </label>
                <input
                  type="date"
                  name="invoiceDate"
                  required
                  value={formData.invoiceDate}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Due Date *
                </label>
                <input
                  type="date"
                  name="dueDate"
                  required
                  value={formData.dueDate}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Description *
              </label>
              <textarea
                name="description"
                required
                value={formData.description}
                onChange={handleChange}
                rows={3}
                placeholder="Describe the services/products..."
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Notes
              </label>
              <textarea
                name="notes"
                value={formData.notes}
                onChange={handleChange}
                rows={2}
                placeholder="Additional notes..."
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              />
            </div>

            <div className="flex gap-3">
              <button
                type="submit"
                className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg font-semibold transition-colors"
              >
                {editingInvoice ? 'Update Invoice' : 'Submit Invoice'}
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowForm(false);
                  setEditingInvoice(null);
                }}
                className="bg-gray-200 hover:bg-gray-300 text-gray-700 px-6 py-2 rounded-lg font-semibold transition-colors"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      {/* View Invoice Modal */}
      {viewingInvoice && ReactDOM.createPortal(
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-9999 p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            <div className="sticky top-0 bg-white border-b bord
            
            6 py-4 flex items-center justify-between">
              <h3 className="text-2xl font-bold text-gray-900">Invoice Details</h3>
              <button onClick={() => setViewingInvoice(null)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            <div className="p-6 space-y-4">
              <div className="bg-blue-50 rounded-lg p-4">
                <p className="text-sm text-gray-600 mb-1">Invoice Number</p>
                <p className="text-xl font-mono font-bold text-blue-600">{viewingInvoice.invoiceNumber}</p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm font-semibold text-gray-600 mb-1">Amount</p>
                  <p className="text-lg font-bold text-gray-900">{formatCurrency(viewingInvoice.amount)}</p>
                </div>
                <div>
                  <p className="text-sm font-semibold text-gray-600 mb-1">Status</p>
                  {getStatusBadge(viewingInvoice.status)}
                </div>
                <div>
                  <p className="text-sm font-semibold text-gray-600 mb-1">Invoice Date</p>
                  <p className="text-gray-900">{formatDate(viewingInvoice.invoiceDate)}</p>
                </div>
                <div>
                  <p className="text-sm font-semibold text-gray-600 mb-1">Due Date</p>
                  <p className="text-gray-900">{formatDate(viewingInvoice.dueDate)}</p>
                </div>
              </div>

              <div>
                <p className="text-sm font-semibold text-gray-600 mb-1">Description</p>
                <p className="text-gray-900 whitespace-pre-wrap">{viewingInvoice.description}</p>
              </div>

              {viewingInvoice.notes && (
                <div>
                  <p className="text-sm font-semibold text-gray-600 mb-1">Notes</p>
                  <p className="text-gray-900 whitespace-pre-wrap">{viewingInvoice.notes}</p>
                </div>
              )}

              <div className="pt-4 border-t border-gray-200">
                <p className="text-sm text-gray-500">Submitted: {formatDate(viewingInvoice.submittedAt)}</p>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={() => handleDownload(viewingInvoice)}
                  className="flex-1 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg flex items-center justify-center gap-2"
                >
                  <Download size={18} />
                  Download
                </button>
                {canEdit(viewingInvoice) && (
                  <button
                    onClick={() => {
                      setViewingInvoice(null);
                      handleEdit(viewingInvoice);
                    }}
                    className="flex-1 bg-gray-600 hover:bg-gray-700 text-white px-4 py-2 rounded-lg flex items-center justify-center gap-2"
                  >
                    <Edit size={18} />
                    Edit
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>,
        document.body
      )}

      {/* Search Bar */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={20} />
          <input
            type="text"
            placeholder="Search invoices by number or description..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      {/* Invoices List */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-visible">{/* Changed to overflow-visible */}
        {filteredInvoices.length === 0 ? (
          <div className="p-12 text-center">
            <FileText className="w-16 h-16 text-gray-300 mx-auto mb-4" />
            <p className="text-gray-500 mb-4">
              {searchTerm ? 'No invoices found' : 'No invoices submitted yet'}
            </p>
            {!searchTerm && vendor.status === 'Approved' && (
              <button
                onClick={() => setShowForm(true)}
                className="text-blue-600 hover:text-blue-700 font-semibold"
              >
                Submit your first invoice
              </button>
            )}
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="text-left px-6 py-4 text-sm font-bold text-gray-700">Invoice #</th>
                  <th className="text-left px-6 py-4 text-sm font-bold text-gray-700">Date</th>
                  <th className="text-left px-6 py-4 text-sm font-bold text-gray-700">Due Date</th>
                  <th className="text-left px-6 py-4 text-sm font-bold text-gray-700">Amount</th>
                  <th className="text-left px-6 py-4 text-sm font-bold text-gray-700">Description</th>
                  <th className="text-left px-6 py-4 text-sm font-bold text-gray-700">Status</th>
                  <th className="text-right px-6 py-4 text-sm font-bold text-gray-700 w-32">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {filteredInvoices.map((invoice) => (
                  <tr key={invoice.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4">
                      <span className="font-mono text-sm font-semibold text-gray-900">
                        {invoice.invoiceNumber}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600">
                      {formatDate(invoice.invoiceDate)}
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600">
                      {formatDate(invoice.dueDate)}
                    </td>
                    <td className="px-6 py-4">
                      <span className="font-semibold text-gray-900">
                        {formatCurrency(invoice.amount)}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600 max-w-xs truncate">
                      {invoice.description}
                    </td>
                    <td className="px-6 py-4">
                      {getStatusBadge(invoice.status)}
                    </td>
                    <td className="px-6 py-4 relative">
                      <div className="flex items-center justify-end">
                        {/* Actions Dropdown - All actions inside */}
                        <div className="relative inline-block">
                          <button
                            onClick={(e) => {
                              if (openDropdown === invoice.id) {
                                setOpenDropdown(null);
                              } else {
                                const rect = e.currentTarget.getBoundingClientRect();
                                setDropdownPosition({
                                  top: rect.bottom + window.scrollY + 4,
                                  right: window.innerWidth - rect.right,
                                });
                                setOpenDropdown(invoice.id);
                              }
                            }}
                            className="text-gray-600 hover:text-gray-900 hover:bg-gray-100 p-2 rounded-lg transition-colors"
                            title="Actions"
                          >
                            <MoreVertical size={20} />
                          </button>

                          {openDropdown === invoice.id && (
                            <>
                              {/* Backdrop to close dropdown */}
                              <div
                                className="fixed inset-0 z-40"
                                onClick={() => setOpenDropdown(null)}
                              ></div>

                              {/* Dropdown Menu - fixed position to escape table overflow */}
                              <div
                                className="fixed w-48 bg-white rounded-lg shadow-xl border border-gray-200 py-1 z-50"
                                style={{ top: dropdownPosition.top, right: dropdownPosition.right }}
                              >
                                {/* View Option - Always available */}
                                <button
                                  onClick={() => handleView(invoice)}
                                  className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 flex items-center gap-2"
                                >
                                  <Eye size={16} />
                                  View Invoice
                                </button>
                                
                                {/* Download Option - Always available */}
                                <button
                                  onClick={() => handleDownload(invoice)}
                                  className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 flex items-center gap-2"
                                >
                                  <Download size={16} />
                                  Download
                                </button>
                                
                                {/* Edit Option - Conditional */}
                                {canEdit(invoice) && (
                                  <>
                                    <div className="border-t border-gray-200 my-1"></div>
                                    <button
                                      onClick={() => handleEdit(invoice)}
                                      className="w-full text-left px-4 py-2 text-sm text-blue-600 hover:bg-blue-50 flex items-center gap-2"
                                    >
                                      <Edit size={16} />
                                      Edit Invoice
                                    </button>
                                  </>
                                )}
                                
                                {/* Delete Option - Conditional */}
                                {canDelete(invoice) && (
                                  <button
                                    onClick={() => handleDelete(invoice)}
                                    className="w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-red-50 flex items-center gap-2"
                                  >
                                    <Trash2 size={16} />
                                    Delete Invoice
                                  </button>
                                )}
                              </div>
                            </>
                          )}
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Delete Confirmation Modal */}
      {deleteConfirmModal && ReactDOM.createPortal(
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-9999 p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full">
            <div className="p-6">
              <div className="flex items-center justify-center w-12 h-12 bg-red-100 rounded-full mx-auto mb-4">
                <Trash2 className="w-6 h-6 text-red-600" />
              </div>
              <h3 className="text-xl font-bold text-gray-900 text-center mb-2">Delete Invoice?</h3>
              <p className="text-gray-600 text-center mb-6">
                Are you sure you want to delete invoice <span className="font-mono font-semibold">{deleteConfirmModal.invoiceNumber}</span>?
                This action cannot be undone.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => setDeleteConfirmModal(null)}
                  className="flex-1 bg-gray-200 hover:bg-gray-300 text-gray-700 px-4 py-2 rounded-lg font-semibold transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={confirmDelete}
                  className="flex-1 bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg font-semibold transition-colors"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>,
        document.body
      )}

      {/* Info Box */}
      <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-lg">
        <h3 className="font-semibold text-blue-900 mb-2">Invoice Status Flow</h3>
        <ul className="text-sm text-blue-800 space-y-1">
          <li>• <strong>Submitted:</strong> Invoice sent to Onction for review</li>
          <li>• <strong>Pending Approval:</strong> Awaiting admin price approval</li>
          <li>• <strong>Under Review:</strong> Admin is reviewing the invoice</li>
          <li>• <strong>Approved:</strong> Invoice approved and ready for payment</li>
          <li>• <strong>Paid:</strong> Payment has been processed</li>
        </ul>
      </div>
    </div>
  );
};

export default VendorInvoicesView;